spring:
  application:
    name: Bike Rental App

  config:
    import: optional:secrets.yaml

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
        hibernate.jdbc.time_zone: UTC

  jackson:
    time-zone: UTC


server:
  port: 4080



